[tasks.test]
clear = true
command = "cargo"
# test target can be optionally specified like `cargo make test html_macro`,
args = ["test", "${@}"]

[tasks.test-overwrite]
extend = "test"
env = { TRYBUILD = "overwrite" }
